### ISSUE TITLE
Declaring arrays on the stack

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#11]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/src/dpu/dpu_task.c#L28

Be aware of what is happening here. You have declared 2 arrays on the stack; each with 312*4 bytes, which eats up >2KB of your WRAM!

**Comment by johnramsden** [comment]
Definitely something I will keep in mind.
