### ISSUE TITLE
Useless shift

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#17]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/src/hdc/aux_functions.c#L80

I am trying to figure out what this one is doing:
majority = majority | (((chHV[j][i] & ( 1 << z)) >> z) << j);

Let's treat 'chHV[j][i]' as a constant:
majority = majority | (((value & ( 1 << z)) >> z) << j);

They are shifting the '1' to extract a bit 'z' from 'value'. Then, they shift the whole value by 'z' bits. I believe this equivalent, and one less shift:
majority = majority | (((value >> z) & 1) << j);

**Comment by johnramsden** [comment]
For reasons unexplainable by myself currently, the implementation with one less shift takes as a whole `1480976` _more_ cycles throughout the entire run of the program. I tried counting the cycles of _just_ running the one line and ended up with zero cycles for both of them so I am having trouble explaining the extra cycles.

Leaving it as the original for now.

**Comment by johnramsden** [comment]
Never mind, is faster. Commiting change.
