### ISSUE TITLE
defining TEST

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#9]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/include/init.h#L21

Are you sure you want this here? I suggest to make it part of the compiler flags by using -DTEST. That gives you more control without having to modify your source code all the time. You could even make this a parameter to the Makefile which will include the compiler flag which is really convenient.

**Comment by johnramsden** [comment]
The way the data is structured should probably be completely rethought (related to #10), keeping it in its current form I've made it configurable from the Makefile.

This _is_ the way the data is generated from Matlab, so we will lose the ability to easily generate data and use it directly from their output. This will likely be not a common occurrence though (if we even decide to generate our own data).
